#!/bin/bash

res=`curl https://raw.githubusercontent.com/halochou/http-hb/master/hb_src.txt 2> /dev/null`

while [ $res != "offline" ]
do
  res=`curl https://raw.githubusercontent.com/halochou/http-hb/master/hb_src.txt 2> /dev/null`
  sleep 300
done
poweroff
